
####################################
######     Global start     ######
####################################
name                : 'TeamMood'
title               : 'TeamMood - How is Your Team Feeling Today?'
email               : hello@teammood.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl             : "" # the subpath of your site, e.g. /blog
url                 : "2020.teammood.com"
favicon: 'img/favicon.png'

# Build settings
markdown            : kramdown

sass:
  sass_dir: _sass

# google_analytics
google_analytics: ''


hero: 'sass_fixed_image'


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

####################################
######      Global end      ######
####################################


####################################
######  feature Section   ######
####################################

feature_image_one: 'img/feature/i1.png'
feature_title_one: 'Collaboration'
feature_description_one: 'Some days a motivational quote can provide a quick pick-me-up for employees and even  management.'

feature_image_two: 'img/feature/i3.png'
feature_title_two: 'Full of features'
feature_description_two: 'Some days a motivational quote can provide a quick pick-me-up for employees and even management.'

feature_image_three: 'img/feature/i4.png'
feature_title_three: 'Global Framework'
feature_description_three: 'Some days a motivational quote can provide a quick pick-me-up for employees and even management.'


####################################
######  marketing Section   ######
####################################
marketing_title: 'Build Your Brand  Automate Your Marketing'
marketing_description: 'The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools to help prevent getting infected. Spyware scan review is a free service for anyone interested in downloading spyware/adware removal software. Our adware remover is the most trusted.'
marketing_image_one: '/img/marketing/d1.png'
marketing_image_two: '/img/marketing/d2.png'
marketing_btn_text: 'Browse free demo'
marketing_btn_link: '#'


####################################
######    cta Section      ######
####################################
cta_title: 'Fallen in Love with <br> our features? Get a free trial for 14 days!'
cta_btn_link_one: '#'
cta_btn_text_one: 'Start free trial'
cta_btn_link_two: '#'
cta_btn_text_two: 'Signup'

####################################
######    Social Section      ######
####################################
social_title: 'Manage Social Network with Our Managing Toolkit'
social_description: 'The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools to help prevent getting infected. Spyware scan review is a free service for anyone interested in downloading spyware/adware removal software. Our adware remover is the most trusted.'
social_image: 'img/social-img.png'
social_button_text: 'Browse free demo'
social_button_link: '#'


#####################################
########## Pricing Tables ###########
#####################################
pricing-table-title: 'Select your Best Pricing'
pricing-table-description: "The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools getting infected. "

# Personal Plan
plan-starter-name: starter
plan-starter-tagline: Small business holders
plan-starter-price: '<span>£29</span>/mo'
plan-starter-offer-line-1-info:  2 User permission
plan-starter-offer-line-2-info:  Customization Allowed 
plan-starter-offer-line-3-info:  Social media tool Enabled 
plan-starter-offer-line-4-info:  No Online Support 
plan-starter-offer-line-5-info:  6 Months Backup 
plan-starter-url: '#'
plan-starter-btn_text: 'Get Started'

# Team Plan
plan-standard-name: standard
plan-standard-tagline: Small business holders
plan-standard-price: '<span>£49</span>/mo'
plan-standard-offer-line-1-info: 2 User permission 
plan-standard-offer-line-2-info: Customization Allowed 
plan-standard-offer-line-3-info: Social media tool Enabled 
plan-standard-offer-line-4-info: No Online Support 
plan-standard-offer-line-5-info:  6 Months Backup 
plan-standard-url: '#'
plan-standard-btn_text: 'Get Started'


# business Plan
plan-business-name: premium
plan-business-tagline: Small business holders
plan-business-price: '<span>£99</span>/mo'
plan-business-offer-line-1-info: 2 User permission 
plan-business-offer-line-2-info: Customization Allowed 
plan-business-offer-line-3-info: Social media tool Enabled 
plan-business-offer-line-4-info: No Online Support 
plan-personal-offer-line-5-info: 6 Months Backup 
plan-business-url: '#'
plan-business-btn_text: 'Get Started'




#####################################
########## Unique Feature ###########
#####################################

unique_feature_title: 'Features that make us Stand Out'
unique_feature_description: 'The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools getting infected.'
unique_feature_image: 'img/title-icon.png' 

unique_feature_main_image_slider: 
  - image: 'img/carusel/c1.png'
  - image: 'img/carusel/c2.png'
  - image: 'img/carusel/c3.png'

unique_feature_section_one_title: 'Certifications'
unique_feature_section_one_description: 'We all live in an age that belongs to the young at heart. Life that is becoming extremely fast, day to day, also asks us to remain.'
unique_feature_section_one_image: http://127.0.0.1:4000/img/feature/f1.png
unique_feature_section_one_link: '#'

unique_feature_section_two_title: 'Page Builder'
unique_feature_section_two_description: 'Vera sought out counseling with me because her doctor advised her to discover the emotional causes of her chronic fatigue.'
unique_feature_section_two_image: http://127.0.0.1:4000/img/feature/f2.png
unique_feature_section_two_link: '#'


#####################################
######## important points ###########
#####################################

important_points_title: 'Features that make us Stand Out'
important_points_description: 'The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools getting infected.'
important_points_image: 'img/title-icon.png' 

important_points:
  - title: 'Search <br> Management<br> System'
    icon: 'img/points/i1.png'
    description: 'Staying calm, composed and maintaining strong self esteem in today’s tough environment can be difficult but is not impossible if you follow a few simple guidelines.'
  - title: 'Data <br> Synchronization <br> Options'
    icon: 'img/points/i2.png'
    description: ' We all live in an age that belongs to the young at heart. Life that is becoming extremely fast, day to day, also asks us to remain physically young. Young at heart. '
  - title: 'Team <br> Management <br> Facilities'
    icon: 'img/points/i3.png'
    description: ' Increasing prosperity in our lives can be accomplished by having the right frame of mind. The truth is, our thoughts are very powerful. They are capable of influencing. '
  - title: 'Schedule <br> Adjustment <br> System'
    icon: 'img/points/i4.png'
    description: ' Have you ever had a problem with a burned light? Thanks to the effort of Thomas Edison we no longer need to invent a light bulb. We just go to the store.  '




#####################################
#########  Brands Section ###########
#####################################
 
bands_slider:
  - image: 'img/brands/woodside.png'
    link: '#'
  - image: 'img/brands/anz.png'
    link: '#'
  - image: 'img/brands/nike.png'
    link: '#'
  - image: 'img/brands/axelspringer.png'
    link: '#'
  - image: 'img/brands/decathlon.png'
    link: '#'
  - image: 'img/brands/ebay.png'
    link: '#'




#####################################
########### Testimonials ############
#####################################

testimonials:

# Client
- author: 'Travor James'
  avatar: '/img/review/user.png'
  position: 'Head of Marketing, Apple Inc.'
  quotes: 'Who are in extremely love with eco friendly system. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'


# Client
- author: 'Travor James'
  avatar: '/img/review/user.png'
  position: 'Head of Marketing, Apple Inc.'
  quotes: 'Who are in extremely love with eco friendly system. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'


# Client
- author: 'Travor James'
  avatar: '/img/review/user.png'
  position: 'Head of Marketing, Apple Inc.'
  quotes: 'Who are in extremely love with eco friendly system. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'


# Client
- author: 'Travor James'
  avatar: '/img/review/user.png'
  position: 'Head of Marketing, Apple Inc.'
  quotes: 'Who are in extremely love with eco friendly system. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'


# Client
- author: 'Travor James'
  avatar: '/img/review/user.png'
  position: 'Head of Marketing, Apple Inc.'
  quotes: 'Who are in extremely love with eco friendly system. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'


# Client
- author: 'Travor James'
  avatar: '/img/review/user.png'
  position: 'Head of Marketing, Apple Inc.'
  quotes: 'Who are in extremely love with eco friendly system. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
#####################################
##########      FAQ       ###########
#####################################
faq-title: 'Select your Best Pricing'
faq-description: "The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools getting infected. "

#General Issues

faq_general_issues_01_title: 'Dude You Re Getting A Telescope'
faq_general_issues_01_description: 'Nunc placerat mi id nisi interdum mollis. Praesent pharetra, justo ut scelerisque mattis, leo quam aliquet diam, congue laoreet elit metus eget diam. Proin ac metus diam.'

faq_general_issues_02_title: 'The Basics Of Buying A Telescope'
faq_general_issues_02_description: 'Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis. leo quam aliquet diam, congue laoreet elit metus eget diam.'

faq_general_issues_03_title: 'Astronomy Binoculars A Great Alternative'
faq_general_issues_03_description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit. Pellentesque aliquet nibh nec urna. Proin ac metus diam.'

faq_general_issues_04_title: 'Do Your Self Realizations Quickly Fade'
faq_general_issues_04_description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit. Pellentesque aliquet nibh nec urna. Proin ac metus diam.'

faq_general_issues_05_title: 'Success Steps For Your Personal Or Business Life'
faq_general_issues_05_description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit. Pellentesque aliquet nibh nec urna. Proin ac metus diam.'


#Support Issues


faq_support_issues_01_title: 'Success Steps For Your Personal Or Business Life'
faq_support_issues_01_description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit. Pellentesque aliquet nibh nec urna. Proin ac metus diam.'

faq_support_issues_02_title: 'Dude You Re Getting A Telescope'
faq_support_issues_02_description: 'Nunc placerat mi id nisi interdum mollis. Praesent pharetra, justo ut scelerisque mattis, leo quam aliquet diam, congue laoreet elit metus eget diam. Proin ac metus diam.'

faq_support_issues_03_title: 'The Basics Of Buying A Telescope'
faq_support_issues_03_description: 'Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis. leo quam aliquet diam, congue laoreet elit metus eget diam.'

faq_support_issues_04_title: 'Astronomy Binoculars A Great Alternative'
faq_support_issues_04_description: 


#Refund Issues

faq_refund_issues_01_title: 'The Basics Of Buying A Telescope'
faq_refund_issues_01_description: 'Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis. leo quam aliquet diam, congue laoreet elit metus eget diam.'

faq_refund_issues_02_title: 'Astronomy Binoculars A Great Alternative'
faq_refund_issues_02_description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit. Pellentesque aliquet nibh nec urna. Proin ac metus diam.'

faq_refund_issues_03_title: 'Do Your Self Realizations Quickly Fade'
faq_refund_issues_03_description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit. Pellentesque aliquet nibh nec urna. Proin ac metus diam.'

faq_refund_issues_04_title: 'Success Steps For Your Personal Or Business Life'
faq_refund_issues_04_description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit. Pellentesque aliquet nibh nec urna. Proin ac metus diam.'




#####################################
##########     Blog      ###########
#####################################
blog-title: 'Latest Posts from our Blog'
blog-description: 'The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools getting infected.'


#####################################
##########     Contact      ###########
#####################################
contact_title: 'Whenever You Need, Just Send a Message'
contact_description: 'The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools getting infected.'
contact_image: 'img/title-icon.png'
contact_email: 'support@demo.com'
contact_phone: '00 (440) 9865 562 9865'
contact_address: 'Los Angeles, United States'

#####################################
##########     footer      ###########
#####################################

footer_title: 'About Us'
footer_description: 'About 64% of all on-line teens say that do things online that they wouldn’t want their parents to know about. 11% of all adult internet user visit websites.'

footer_resources_link_heading: 'Resources'
footer_resources_link_one_text: 'Guides'
footer_resources_link_one_link: '#'
footer_resources_link_two_text: 'Research'
footer_resources_link_one_link: '#'
footer_resources_link_three_text: 'Experts'
footer_resources_link_one_link: '#'
footer_resources_link_four_text: 'Agencies'
footer_resources_link_one_link: '#'


footer_features_link_heading: 'Features'
footer_features_link_one_text: 'Guides'
footer_features_link_one_link: '#'
footer_features_link_two_text: 'Research'
footer_features_link_one_link: '#'
footer_features_link_three_text: 'Experts'
footer_features_link_one_link: '#'
footer_features_link_four_text: 'Agencies'
footer_features_link_one_link: '#'


footer_facebook_link: '#'
footer_twitter_link: '#'
footer_dribbble_link: '#'
footer_behance_link: '#'

mailchimp:
  user-id: 
  list-id: 


####################################
######        Copyright       ######
####################################
copyright_text: Copyright © 2019 All rights reserved to
company_url: '#'


# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
